"""
gen_macro_reference.py   Generate MDX reference pages from dbt macro docstrings.

Parses {#- ... -#} Jinja docstring comments from transform/target/manifest.json
macro_sql fields and writes one .mdx file per macro to
docs/reference/macros/<macro_name>.mdx.

Also writes/updates docs/reference/macros/index.md.

Run: python scripts/gen_macro_reference.py
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mdx_utils import escape_mdx

REPO_ROOT = Path(__file__).parent.parent
MANIFEST_PATH = REPO_ROOT / "transform" / "target" / "manifest.json"
OUT_DIR = REPO_ROOT / "docs" / "docs" / "reference" / "macros"

AUTOGEN_HEADER = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_macro_reference.py` to regenerate. */}"
AUTOGEN_HEADER_MD = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_macro_reference.py` to regenerate. */}"

# Regex to extract the {#- ... -#} docstring block
_DOCSTRING_RE = re.compile(r"\{#-\s*(.*?)\s*-#\}", re.DOTALL)
# Regex to extract macro signature: {% macro name(args) %}
_SIGNATURE_RE = re.compile(r"\{%\s*macro\s+(\w+)\s*\(([^)]*)\)\s*%\}")


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}")
        print("Run: cd transform && dbt parse --profiles-dir profiles")
        sys.exit(1)
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def parse_docstring(macro_sql: str) -> dict:
    """
    Extract structured info from a Jinja {#- ... -#} docstring block.

    Returns a dict with keys: description, args, returns, notes, usage_example.
    """
    match = _DOCSTRING_RE.search(macro_sql)
    if not match:
        return {"description": "", "args": [], "returns": "", "notes": "", "usage_example": ""}

    raw = match.group(1)
    lines = [line.rstrip() for line in raw.splitlines()]

    description_lines: list[str] = []
    args: list[tuple[str, str]] = []
    returns = ""
    notes_lines: list[str] = []
    usage_lines: list[str] = []

    # Section headers   may or may not have inline content
    _SECTION_HEADERS = {
        r"^Args?:\s*(.*)$": "args",
        r"^Returns?:\s*(.*)$": "returns",
        r"^(Usage|Example):\s*(.*)$": "usage",
        r"^(Sources?|Notes?|Given|Normal-normal):\s*(.*)$": "notes",
    }

    section = "description"
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Check if this line is a section header
        switched = False
        for pattern, new_section in _SECTION_HEADERS.items():
            m = re.match(pattern, stripped, re.IGNORECASE)
            if m:
                section = new_section
                # Some headers have inline content after the colon
                inline = m.group(m.lastindex).strip() if m.lastindex else ""
                if inline:
                    if section == "returns":
                        returns = inline
                    elif section == "notes":
                        notes_lines.append(inline)
                switched = True
                break

        if switched:
            i += 1
            continue

        if section == "description":
            description_lines.append(stripped)
        elif section == "args":
            # Match "  arg_name:  description text" or "  arg_name (type):  description"
            arg_match = re.match(r"\s{2,}(\w+)(?:\s*\([^)]*\))?:\s*(.*)", line)
            if arg_match:
                args.append((arg_match.group(1), arg_match.group(2).strip()))
            elif stripped and args:
                # Continuation of previous arg description
                prev_name, prev_desc = args[-1]
                args[-1] = (prev_name, f"{prev_desc} {stripped}")
        elif section == "returns":
            if stripped:
                returns = stripped if not returns else f"{returns} {stripped}"
        elif section == "usage":
            usage_lines.append(line)
        elif section == "notes":
            notes_lines.append(stripped)
        i += 1

    description = " ".join(l for l in description_lines if l).strip()
    notes = "\n".join(l for l in notes_lines if l).strip()
    usage_example = "\n".join(usage_lines).strip()

    return {
        "description": description,
        "args": args,
        "returns": returns,
        "notes": notes,
        "usage_example": usage_example,
    }


def parse_signature_args(macro_sql: str) -> list[str]:
    match = _SIGNATURE_RE.search(macro_sql)
    if not match:
        return []
    args_str = match.group(2).strip()
    if not args_str:
        return []
    return [a.strip() for a in args_str.split(",") if a.strip()]


def render_macro_mdx(macro: dict) -> str:
    name = macro["name"]
    macro_sql = macro.get("macro_sql", "")

    doc = parse_docstring(macro_sql)
    sig_args = parse_signature_args(macro_sql)

    signature = f"{name}({', '.join(sig_args)})" if sig_args else f"{name}()"

    lines = [
        AUTOGEN_HEADER,  # JSX comment for .mdx
        "",
        f"# `{name}`",
        "",
    ]

    if doc["description"]:
        lines += [escape_mdx(doc["description"]), ""]

    lines += [
        "## Signature",
        "",
        "```sql",
        f"{{{{ {signature} }}}}",
        "```",
        "",
    ]

    if doc["args"]:
        lines += [
            "## Arguments",
            "",
            "| Argument | Description |",
            "|---|---|",
        ]
        for arg_name, arg_desc in doc["args"]:
            arg_desc = escape_mdx(arg_desc.replace("|", "\\|"))
            lines.append(f"| `{arg_name}` | {arg_desc} |")
        lines.append("")

    if doc["returns"]:
        lines += ["## Returns", "", escape_mdx(doc["returns"]), ""]

    if doc["notes"]:
        lines += ["## Notes", "", escape_mdx(doc["notes"]), ""]

    if doc["usage_example"]:
        lines += [
            "## Usage",
            "",
            "```sql",
            doc["usage_example"],
            "```",
            "",
        ]

    return "\n".join(lines)


def render_index(macros: list[dict]) -> str:
    lines = [
        AUTOGEN_HEADER_MD,  # HTML comment for .md
        "",
        "---",
        "id: macros-index",
        "slug: /reference/macros",
        "sidebar_position: 1",
        "title: dbt Macros",
        "---",
        "",
        "# dbt Macros Reference",
        "",
        f"Auto-generated reference for all {len(macros)} project macros.",
        "",
        "| Macro | Description |",
        "|---|---|",
    ]

    for macro in sorted(macros, key=lambda m: m["name"]):
        name = macro["name"]
        doc = parse_docstring(macro.get("macro_sql", ""))
        desc = doc["description"]
        first_sentence = desc.split(".")[0] + "." if "." in desc else desc
        first_sentence = first_sentence.replace("|", "\\|") if first_sentence else " "
        lines.append(f"| [`{name}`](/reference/macros/{name}) | {first_sentence} |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    manifest = load_manifest()
    macros_all = manifest["macros"]
    project_macros = [
        v for v in macros_all.values()
        if v.get("package_name") == "off_the_pace"
    ]

    if not project_macros:
        print("No project macros found in manifest.")
        return

    print(f"Found {len(project_macros)} project macros")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for macro in project_macros:
        mdx = render_macro_mdx(macro)
        out_path = OUT_DIR / f"{macro['name']}.mdx"
        out_path.write_text(mdx, encoding="utf-8")

    index_path = OUT_DIR / "index.md"
    index_path.write_text(render_index(project_macros), encoding="utf-8")

    print(f"Wrote {len(project_macros)} macro pages + index → {OUT_DIR}")


if __name__ == "__main__":
    main()
