"""
gen_dbt_reference.py   Generate MDX reference pages from dbt manifest.json.

Reads transform/target/manifest.json and writes one .mdx file per model to
docs/reference/models/<model_name>.mdx.

Also writes/updates docs/reference/models/index.md with a table of all models.

Run: python scripts/gen_dbt_reference.py
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mdx_utils import escape_mdx

REPO_ROOT = Path(__file__).parent.parent
MANIFEST_PATH = REPO_ROOT / "transform" / "target" / "manifest.json"
OUT_DIR = REPO_ROOT / "docs" / "reference" / "models"

AUTOGEN_HEADER = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_dbt_reference.py` to regenerate. */}"
AUTOGEN_HEADER_MD = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_dbt_reference.py` to regenerate. */}"

LAYER_ORDER = ["staging", "intermediate", "marts", "reference"]
LAYER_LABELS = {
    "staging": "Staging",
    "intermediate": "Intermediate",
    "marts": "Marts",
    "reference": "Reference",
}

# Maps model name prefix → explanation page slug (for cross-ref links)
EXPLANATION_LINKS: dict[str, str] = {
    "int_lap_residual_decomposed": "/decomposition/seven-term-identity",
    "fct_lap_residuals": "/decomposition/seven-term-identity",
    "int_dirty_air_tax_component": "/decomposition/methodology",
    "int_compound_cliff_predicted": "/decomposition/methodology",
    "fct_cliff_prediction_features": "/decomposition/methodology",
}


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}")
        print("Run: cd transform && dbt parse --profiles-dir profiles")
        sys.exit(1)
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def collect_tests_by_model(nodes: dict) -> dict[str, list[dict]]:
    """Index test nodes by the model unique_id they are attached to."""
    index: dict[str, list[dict]] = {}
    for node in nodes.values():
        if node["resource_type"] != "test":
            continue
        attached = node.get("attached_node")
        if not attached:
            continue
        meta = node.get("test_metadata", {})
        index.setdefault(attached, []).append(
            {
                "name": meta.get("name", node["name"]),
                "column_name": node.get("column_name"),
                "kwargs": meta.get("kwargs", {}),
            }
        )
    return index


def tests_for_column(model_uid: str, col_name: str, tests_index: dict) -> list[str]:
    model_tests = tests_index.get(model_uid, [])
    return [
        t["name"]
        for t in model_tests
        if t.get("column_name") == col_name
    ]


def model_tests_no_column(model_uid: str, tests_index: dict) -> list[str]:
    model_tests = tests_index.get(model_uid, [])
    return [
        t["name"]
        for t in model_tests
        if not t.get("column_name")
    ]


def upstream_models(node: dict, nodes: dict) -> list[str]:
    deps = node.get("depends_on", {}).get("nodes", [])
    return [
        nodes[d]["name"]
        for d in deps
        if d in nodes and nodes[d]["resource_type"] == "model"
    ]


LAYER_SUBDIR = {
    "staging": "stg",
    "intermediate": "int",
    "reference": "dim",
    "marts": "fct",
}


def layer_of(node: dict) -> str:
    path = node.get("path", "")
    return path.split("/")[0] if "/" in path else "other"


def subdir_of(name: str) -> str:
    for prefix, subdir in [("stg_", "stg"), ("int_", "int"), ("dim_", "dim"), ("fct_", "fct")]:
        if name.startswith(prefix):
            return subdir
    return "other"


def model_link(source_subdir: str, target_name: str) -> str:
    target_subdir = subdir_of(target_name)
    if target_subdir == source_subdir:
        return f"[`{target_name}`](./{target_name})"
    return f"[`{target_name}`](../{target_subdir}/{target_name})"


def render_model_mdx(node: dict, tests_index: dict, nodes: dict) -> str:
    name = node["name"]
    description = escape_mdx(node.get("description", "").strip())
    layer = layer_of(node)
    source_subdir = subdir_of(name)
    tags = [t for t in node.get("tags", []) if t != layer]
    columns = node.get("columns", {})
    contract_enforced = node.get("contract", {}).get("enforced", False)
    uid = node["unique_id"]
    upstream = upstream_models(node, nodes)
    model_level_tests = model_tests_no_column(uid, tests_index)

    lines = [
        AUTOGEN_HEADER,  # JSX comment   valid in .mdx
        "",
        f"# `{name}`",
        "",
    ]

    if name in EXPLANATION_LINKS:
        lines += [
            f"> For the conceptual foundation, read [{name.replace('_', ' ').title()}]({EXPLANATION_LINKS[name]}).",
            "",
        ]

    if description:
        lines += [description, ""]

    # Metadata table
    lines += ["## Overview", "", "| Property | Value |", "|---|---|"]
    lines.append(f"| Layer | `{layer}` |")
    lines.append(f"| Contract enforced | {'✅ Yes' if contract_enforced else 'No'} |")
    if tags:
        lines.append(f"| Tags | {', '.join(f'`{t}`' for t in tags)} |")
    if upstream:
        upstream_links = ", ".join(model_link(source_subdir, m) for m in upstream)
        lines.append(f"| Upstream | {upstream_links} |")
    if model_level_tests:
        lines.append(f"| Model-level tests | {', '.join(f'`{t}`' for t in model_level_tests)} |")
    lines.append("")

    # Columns table
    if columns:
        lines += [
            "## Columns",
            "",
            "| Column | Type | Nullable | Tests | Description |",
            "|---|---|---|---|---|",
        ]
        for col_name, col in columns.items():
            col_description = escape_mdx(col.get("description", "").replace("|", "\\|").replace("\n", " ").strip())
            data_type = col.get("data_type") or ""
            constraints = col.get("constraints", [])
            nullable = "No" if any(c.get("type") == "not_null" for c in constraints) else "Yes"
            col_tests = tests_for_column(uid, col_name, tests_index)
            tests_str = ", ".join(f"`{t}`" for t in col_tests) if col_tests else " "
            type_str = f"`{data_type}`" if data_type else " "
            lines.append(f"| `{col_name}` | {type_str} | {nullable} | {tests_str} | {col_description} |")
        lines.append("")
    else:
        lines += ["## Columns", "", "_Column definitions not yet documented in schema.yml._", ""]

    return "\n".join(lines)


def render_index(models_by_layer: dict[str, list[dict]]) -> str:
    lines = [
        AUTOGEN_HEADER_MD,  # HTML comment   valid in .md
        "",
        "---",
        "id: models-index",
        "slug: /reference/models",
        "sidebar_position: 1",
        "title: dbt Models",
        "---",
        "",
        "# dbt Models Reference",
        "",
        f"Auto-generated reference for all {sum(len(v) for v in models_by_layer.values())} dbt models.",
        "",
    ]

    for layer in LAYER_ORDER:
        models = models_by_layer.get(layer, [])
        if not models:
            continue
        label = LAYER_LABELS.get(layer, layer.title())
        lines += [f"## {label}", ""]
        lines += [
            "| Model | Description |",
            "|---|---|",
        ]
        for node in sorted(models, key=lambda n: n["name"]):
            name = node["name"]
            desc = node.get("description", "").strip()
            # First sentence only
            first_sentence = re.split(r"(?<=[.!?])\s", desc)[0] if desc else " "
            first_sentence = escape_mdx(first_sentence.replace("|", "\\|"))
            lines.append(f"| [`{name}`](/reference/models/{subdir_of(name)}/{name}) | {first_sentence} |")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    manifest = load_manifest()
    nodes = manifest["nodes"]

    tests_index = collect_tests_by_model(nodes)

    models = {k: v for k, v in nodes.items() if v["resource_type"] == "model" and v.get("package_name") == "off_the_pace"}

    print(f"Found {len(models)} project models")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    models_by_layer: dict[str, list[dict]] = {}
    for node in models.values():
        layer = layer_of(node)
        models_by_layer.setdefault(layer, []).append(node)

    written = 0
    for node in models.values():
        mdx = render_model_mdx(node, tests_index, nodes)
        subdir = subdir_of(node["name"])
        subdir_path = OUT_DIR / subdir
        subdir_path.mkdir(parents=True, exist_ok=True)
        out_path = subdir_path / f"{node['name']}.mdx"
        out_path.write_text(mdx, encoding="utf-8")
        written += 1

    # Index
    index_path = OUT_DIR / "index.md"
    index_path.write_text(render_index(models_by_layer), encoding="utf-8")

    print(f"Wrote {written} model pages + index → {OUT_DIR}")


if __name__ == "__main__":
    main()
