"""
gen_cli_reference.py   Generate MDX reference pages from CLI --help output.

Scrapes --help output from known CLI commands and writes one .mdx file per command to
docs/reference/cli/<command>.mdx.

Also writes/updates docs/reference/cli/index.md.

Run: python scripts/gen_cli_reference.py
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
OUT_DIR = REPO_ROOT / "docs" / "reference" / "cli"

AUTOGEN_HEADER = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_cli_reference.py` to regenerate. */}"
AUTOGEN_HEADER_MD = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_cli_reference.py` to regenerate. */}"

# (display_name, command_args, description_override)
CLI_COMMANDS: list[tuple[str, list[str], str]] = [
    (
        "ingest",
        [sys.executable, str(REPO_ROOT / "ingestion" / "src" / "ingest.py"), "--help"],
        "Unified F1 Bronze-layer ingestion controller. Fetches race and qualifying data from FastF1 and writes Hive-partitioned Parquet to `data/bronze/`.",
    ),
]


def run_help(command_args: list[str]) -> str:
    result = subprocess.run(
        command_args,
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    # argparse prints --help to stdout; some tools use stderr
    output = result.stdout or result.stderr
    return output.strip()


def parse_argparse_help(raw_help: str) -> dict:
    """Extract usage, description, and options from argparse --help output."""
    lines = raw_help.splitlines()

    usage_lines = []
    description_lines = []
    options_block: list[str] = []
    examples_block: list[str] = []

    section = "usage"
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("usage:"):
            usage_lines.append(stripped)
            section = "usage"
        elif stripped.lower() in ("options:", "optional arguments:", "positional arguments:"):
            section = "options"
        elif stripped.lower() == "examples:":
            section = "examples"
        elif section == "usage" and not stripped.startswith("usage:") and stripped:
            if stripped[0].isalpha() and not stripped.startswith("-"):
                section = "description"
                description_lines.append(stripped)
            else:
                usage_lines.append(stripped)
        elif section == "description":
            if stripped.lower() in ("options:", "optional arguments:", "positional arguments:"):
                section = "options"
            elif stripped.lower() == "examples:":
                section = "examples"
            else:
                description_lines.append(stripped)
        elif section == "options":
            if stripped.lower() == "examples:":
                section = "examples"
            else:
                options_block.append(line)
        elif section == "examples":
            examples_block.append(line)

    return {
        "usage": " ".join(usage_lines),
        "description": " ".join(description_lines).strip(),
        "options_raw": "\n".join(options_block).strip(),
        "examples_raw": "\n".join(examples_block).strip(),
    }


def render_cli_mdx(name: str, raw_help: str, description_override: str) -> str:
    parsed = parse_argparse_help(raw_help)
    description = description_override or parsed["description"]

    lines = [
        AUTOGEN_HEADER,  # JSX comment for .mdx
        "",
        f"# `{name}`",
        "",
    ]

    if description:
        lines += [description, ""]

    if parsed["usage"]:
        lines += [
            "## Usage",
            "",
            "```bash",
            parsed["usage"],
            "```",
            "",
        ]

    if parsed["options_raw"]:
        lines += [
            "## Options",
            "",
            "```",
            parsed["options_raw"],
            "```",
            "",
        ]

    if parsed["examples_raw"]:
        lines += [
            "## Examples",
            "",
            "```bash",
            parsed["examples_raw"],
            "```",
            "",
        ]

    return "\n".join(lines)


def render_index(commands: list[tuple[str, str]]) -> str:
    lines = [
        AUTOGEN_HEADER_MD,  # HTML comment for .md
        "",
        "---",
        "id: cli-index",
        "slug: /reference/cli",
        "sidebar_position: 1",
        "title: CLI Reference",
        "---",
        "",
        "# CLI Reference",
        "",
        "Auto-generated reference for all Off The Pace command-line tools.",
        "",
        "| Command | Description |",
        "|---|---|",
    ]
    for name, desc in commands:
        short_desc = desc.split(".")[0] + "." if "." in desc else desc
        short_desc = short_desc.replace("|", "\\|")
        lines.append(f"| [`{name}`](/reference/cli/{name}) | {short_desc} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    index_entries = []
    written = 0

    for name, command_args, description_override in CLI_COMMANDS:
        print(f"  Scraping --help for {name}...")
        raw_help = run_help(command_args)
        if not raw_help:
            print(f"  WARNING: No output from {command_args}")
            continue
        mdx = render_cli_mdx(name, raw_help, description_override)
        out_path = OUT_DIR / f"{name}.mdx"
        out_path.write_text(mdx, encoding="utf-8")
        index_entries.append((name, description_override))
        written += 1

    index_path = OUT_DIR / "index.md"
    index_path.write_text(render_index(index_entries), encoding="utf-8")

    print(f"Wrote {written} CLI pages + index → {OUT_DIR}")


if __name__ == "__main__":
    main()
