"""
gen_schema_reference.py   Generate MDX reference pages from Bronze JSON Schemas.

Reads ingestion/schemas/*.schema.json and writes one .mdx file per dataset to
docs/reference/schemas/<dataset>.mdx.

Also writes/updates docs/reference/schemas/index.md.

Run: python scripts/gen_schema_reference.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mdx_utils import escape_mdx

REPO_ROOT = Path(__file__).parent.parent
SCHEMAS_DIR = REPO_ROOT / "ingestion" / "schemas"
OUT_DIR = REPO_ROOT / "docs" / "reference" / "schemas"

AUTOGEN_HEADER = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_schema_reference.py` to regenerate. */}"
AUTOGEN_HEADER_MD = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_schema_reference.py` to regenerate. */}"

# Display order for datasets
DATASET_ORDER = ["laps", "telemetry", "weather", "race_control"]


def render_schema_mdx(schema: dict) -> str:
    dataset_id = schema.get("$id", "unknown")
    title = schema.get("title", dataset_id)
    description = schema.get("description", "").strip()
    file_pattern = schema.get("x-file-pattern", "")
    example_row_count = schema.get("x-example-row-count", "")
    notes = schema.get("x-notes", "")
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))

    lines = [
        AUTOGEN_HEADER,  # JSX comment for .mdx
        "",
        f"# {title}",
        "",
    ]

    if description:
        lines += [description, ""]

    lines += ["## Overview", "", "| Property | Value |", "|---|---|"]
    if file_pattern:
        lines.append(f"| File pattern | `{file_pattern}` |")
    if example_row_count:
        lines.append(f"| Example row count | {example_row_count} |")
    lines.append("")

    if notes:
        lines += [f":::note", "", notes, "", ":::", ""]

    if properties:
        lines += [
            "## Columns",
            "",
            "| Column | Type | Nullable | Source | Description |",
            "|---|---|---|---|---|",
        ]
        for col_name, col in properties.items():
            raw_type = col.get("type", "")
            if isinstance(raw_type, list):
                types = [t for t in raw_type if t != "null"]
                nullable = "Yes" if "null" in raw_type else "No"
                type_str = types[0] if types else "unknown"
            else:
                type_str = raw_type
                nullable = "No" if col_name in required else "Yes"

            dtype_override = col.get("x-dtype")
            if dtype_override:
                type_str = dtype_override

            source = col.get("x-source", "")
            col_description = escape_mdx(col.get("description", "").replace("|", "\\|").replace("\n", " ").strip())

            known_issue = col.get("x-known-issue")
            if known_issue:
                col_description += f" ⚠️ *{known_issue}*"

            lines.append(
                f"| `{col_name}` | `{type_str}` | {nullable} | {source} | {col_description} |"
            )
        lines.append("")

    # Required columns callout
    if required:
        required_list = ", ".join(f"`{c}`" for c in sorted(required))
        lines += [
            "## Required Columns",
            "",
            f"These columns are always present (non-null, always ingested): {required_list}.",
            "",
        ]

    return "\n".join(lines)


def render_index(datasets: list[dict]) -> str:
    lines = [
        AUTOGEN_HEADER_MD,  # HTML comment for .md
        "",
        "---",
        "id: schemas-index",
        "slug: /reference/schemas",
        "sidebar_position: 1",
        "title: Bronze Schemas",
        "---",
        "",
        "# Bronze Schemas Reference",
        "",
        "Auto-generated reference for all Bronze-layer datasets ingested from FastF1.",
        "",
        "| Dataset | Description |",
        "|---|---|",
    ]

    for schema in datasets:
        dataset_id = schema.get("$id", "unknown")
        title = schema.get("title", dataset_id)
        desc = schema.get("description", "").strip()
        first_sentence = desc.split(".")[0] + "." if desc else " "
        first_sentence = escape_mdx(first_sentence.replace("|", "\\|"))
        lines.append(f"| [`{title}`](/reference/schemas/{dataset_id}) | {first_sentence} |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    schema_files = sorted(SCHEMAS_DIR.glob("*.schema.json"))
    if not schema_files:
        print(f"ERROR: No schema files found in {SCHEMAS_DIR}")
        print("Expected: laps.schema.json, telemetry.schema.json, weather.schema.json, race_control.schema.json")
        return

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    schemas_in_order = []
    loaded: dict[str, dict] = {}

    for schema_file in schema_files:
        with open(schema_file) as f:
            schema = json.load(f)
        loaded[schema.get("$id", schema_file.stem)] = schema

    for dataset_id in DATASET_ORDER:
        if dataset_id in loaded:
            schemas_in_order.append(loaded[dataset_id])
    for dataset_id, schema in loaded.items():
        if dataset_id not in DATASET_ORDER:
            schemas_in_order.append(schema)

    written = 0
    for schema in schemas_in_order:
        dataset_id = schema.get("$id", "unknown")
        mdx = render_schema_mdx(schema)
        out_path = OUT_DIR / f"{dataset_id}.mdx"
        out_path.write_text(mdx, encoding="utf-8")
        written += 1

    index_path = OUT_DIR / "index.md"
    index_path.write_text(render_index(schemas_in_order), encoding="utf-8")

    print(f"Wrote {written} schema pages + index → {OUT_DIR}")


if __name__ == "__main__":
    main()
