"""
gen_ml_reference.py   Generate the ML model-card MDX from ml/model_card.yml.

Reads ml/model_card.yml (machine-written by ml/src/card.py) and writes:
  docs/docs/reference/ml/degradation-model-v1.mdx
  docs/docs/reference/ml/_category_.json   ("ML Models")

Run:   python scripts/gen_ml_reference.py
Check: python scripts/gen_ml_reference.py --check   # exit 1 if committed MDX drifted (D2)

D2: this generator implements a *real* --check (re-emit in memory, diff vs committed, exit 1 on
drift) AND is registered in scripts/build_reference.py's GENERATORS list, so the existing
`git diff --exit-code docs/docs/reference/` CI gate also covers the ML docs. Belt and braces.
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from mdx_utils import escape_mdx

REPO_ROOT = Path(__file__).parent.parent
CARD_PATH = REPO_ROOT / "ml" / "model_card.yml"
OUT_DIR = REPO_ROOT / "docs" / "docs" / "reference" / "ml"
MDX_PATH = OUT_DIR / "degradation-model-v1.mdx"
CATEGORY_PATH = OUT_DIR / "_category_.json"

AUTOGEN_HEADER = "{/* _AUTOGENERATED   do not hand-edit. Run `python scripts/gen_ml_reference.py` to regenerate. */}"

CATEGORY_JSON = {
    "label": "ML Models",
    "position": 6,
    "link": {"type": "generated-index", "description": "Machine learning layer models (XGBoost)."},
}


def load_card() -> dict:
    if not CARD_PATH.exists():
        print(f"ERROR: model card not found at {CARD_PATH}")
        print("Run: make ml-card   (./.venv/bin/python -m ml.src.card --write)")
        sys.exit(1)
    return yaml.safe_load(CARD_PATH.read_text())["model_card"]


def _fmt(v) -> str:
    return f"{v:.4f}" if isinstance(v, float) else str(v)


def _arrow(metric: str) -> str:
    return "↓ lower better" if metric in ("pinball", "rmse") else "↑ higher better"


def render_mdx(card: dict) -> str:
    L: list[str] = [
        AUTOGEN_HEADER,
        "",
        "---",
        "id: degradation-model-v1",
        "title: Tyre Degradation Predictors (v1)",
        "sidebar_position: 1",
        "---",
        "",
        f"# {escape_mdx(card['name'])} (`{card['version']}`)",
        "",
        escape_mdx(card["summary"]),
        "",
        "> Conceptual foundation: [Methodology](/understand/methodology) · "
        "feature source: [`fct_cliff_prediction_features`](/reference/models/fct/fct_cliff_prediction_features).",
        "",
        "## Intended use",
        "",
        escape_mdx(card["intended_use"]),
        "",
    ]

    # ── Headline table ──
    L += [
        "## Models & headline performance",
        "",
        "Every model is evaluated against a strong per-cohort baseline; all five beat it. "
        f"Validation: {escape_mdx(card['validation']['scheme'])}.",
        "",
        "| Model | Kind | Metric | CV | Eval | Baseline | Beats |",
        "|---|---|---|---|---|---|---|",
    ]
    for m in card["models"]:
        beats = "✅" if m["beats_baseline"] else "⚠️"
        L.append(
            f"| `{m['name']}` | {m['kind']} | {m['headline_metric']} ({_arrow(m['headline_metric'])}) "
            f"| {_fmt(m['cv_headline'])} | {_fmt(m['eval_headline'])} | {_fmt(m['baseline_headline'])} | {beats} |")
    L += ["",
          f"_Eval headline on the {card['data']['evaluation_mode']} "
          f"(season {card['data']['evaluation_season']}); CV is the season-grouped TimeSeriesSplit mean._",
          ""]

    # ── Per-model detail ──
    L += ["## Per-model detail", ""]
    for m in card["models"]:
        L += [f"### `{m['name']}`", "",
              f"- **Family / kind:** {m['family']} / {m['kind']}",
              f"- **Objective:** `{m['objective']}`"
              + (f" (α={m['quantile_alpha']})" if m["quantile_alpha"] is not None else ""),
              f"- **Train rows:** {m['n_train_rows']:,} · **fit:** {m['fit_seconds']}s",
              f"- **Artefacts:** `{m['artefacts']['booster']}` + parity-tested `{m['artefacts']['onnx']}`",
              "", "<details>", "<summary>Hyperparameters</summary>", "",
              "```json", json.dumps(m["hyperparameters"], indent=2), "```", "", "</details>", ""]

    # ── Features ──
    f = card["features"]
    L += ["## Features", "",
          f"{len(f['columns'])} features in {len(f['groups'])} ablation groups. "
          f"Categoricals are ordinal-encoded from the training map (NULL/unseen → −1).", "",
          "| Group | Features |", "|---|---|"]
    for g, cols in f["groups"].items():
        L.append(f"| `{g}` | {', '.join(f'`{c}`' for c in cols)} |")
    L += ["", "### Leakage guards", "",
          escape_mdx(f["excluded_note"]), "",
          "Excluded (identity / target / leakage): "
          + ", ".join(f"`{c}`" for c in f["excluded_leakage"]), ""]

    # ── Validation ──
    v = card["validation"]
    cal = v.get("calibration", {})
    lp = v.get("leakage_probe", {})
    L += ["## Validation", "",
          "### Baselines", "",
          "| Family | Baseline |", "|---|---|"]
    for fam, desc in v["baselines"].items():
        L.append(f"| {fam} | {escape_mdx(desc)} |")
    if cal:
        L += ["", "### Calibration (quantile interval)", "",
              f"Nominal coverage **{cal.get('nominal')}** → raw [p10,p90] empirical "
              f"**{_fmt(cal.get('raw_empirical_coverage', 0))}**, split-conformal "
              f"**{_fmt(cal.get('conformal_empirical_coverage', 0))}** "
              f"(mean interval width {_fmt(cal.get('mean_interval_width', 0))}s).", ""]
    if lp:
        L += ["### Adversarial leakage probe", "",
              f"A throwaway model recovers `race_year` from the features at "
              f"**{_fmt(lp.get('accuracy', 0))}** vs a majority baseline of "
              f"{_fmt(lp.get('majority_class_accuracy', 0))}-{escape_mdx(lp.get('note', ''))}.", ""]
    if v.get("dual_importance"):
        L += ["### Feature importance (SHAP vs permutation)", "",
              "| Model | SHAP top-5 | Permutation top-5 |", "|---|---|---|"]
        for name, imp in v["dual_importance"].items():
            L.append(f"| `{name}` | {', '.join(f'`{x}`' for x in imp['shap_top5'])} "
                     f"| {', '.join(f'`{x}`' for x in imp['permutation_top5'])} |")
        L.append("")

    under = v.get("underperforming_cohorts", [])
    L += ["### Underperforming cohorts", "",
          escape_mdx(v["underperforming_cohorts_note"]), "",
          f"**{len(under)}** cohort cells lose to baseline (surfaced, never dropped):", "",
          "| Dimension | Cohort | n | Model | Baseline |", "|---|---|---|---|---|"]
    for u in under:
        L.append(f"| {u['dimension']} | {escape_mdx(str(u['cohort']))} | {u['n']} "
                 f"| {_fmt(u['model'])} | {_fmt(u['baseline'])} |")
    L.append("")

    # ── Reproducibility + limitations ──
    r = card["reproducibility"]
    L += ["## Reproducibility", "",
          f"- **Seed:** `{r['random_state']}` · **dataset fingerprint:** `{r['dataset_fingerprint'][:16]}…`",
          f"- **Libraries:** {', '.join(f'{k} {ver}' for k, ver in r['library_versions'].items())}",
          f"- **ONNX parity:** {escape_mdx(r['onnx_parity'])}",
          f"- **Reproduce:** `{r['command']}`", "",
          "## Limitations", ""]
    L += [f"- {escape_mdx(x)}" for x in card["limitations"]]
    L += ["", "## Holdout policy", "", escape_mdx(card["data"]["holdout_note"]), ""]
    return "\n".join(L)


def render_all() -> dict[Path, str]:
    card = load_card()
    return {
        MDX_PATH: render_mdx(card),
        CATEGORY_PATH: json.dumps(CATEGORY_JSON, indent=2) + "\n",
    }


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in render_all().items():
        path.write_text(content, encoding="utf-8")
    print(f"Wrote ML reference → {MDX_PATH.relative_to(REPO_ROOT)} (+ _category_.json)")


def check() -> int:
    """Re-emit in memory, diff vs committed; exit 1 on drift (D2)."""
    drift = []
    for path, content in render_all().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            drift.append(path.relative_to(REPO_ROOT))
    if drift:
        print("ML reference drift detected in: " + ", ".join(str(p) for p in drift))
        print("Run `make ml-reference` (or `python scripts/gen_ml_reference.py`) and commit.")
        return 1
    print("ML reference up to date.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if committed MDX drifted")
    args = ap.parse_args()
    sys.exit(check() if args.check else (main() or 0))
