import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  understandSidebar: [
    {
      type: 'category',
      label: 'Understand',
      items: [
        'understand/goal-and-approach',
        'understand/seven-term-identity',
        'understand/methodology',
        'understand/out-of-sample-validation',
        'understand/limitations',
      ],
    },
  ],

  referenceSidebar: [
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'dbt Models',
          items: [
            'reference/models/index',
            {
              type: 'category',
              label: 'Staging',
              items: [{type: 'autogenerated', dirName: 'reference/models/stg'}],
            },
            {
              type: 'category',
              label: 'Intermediates',
              items: [{type: 'autogenerated', dirName: 'reference/models/int'}],
            },
            {
              type: 'category',
              label: 'Dimensions',
              items: [{type: 'autogenerated', dirName: 'reference/models/dim'}],
            },
            {
              type: 'category',
              label: 'Facts',
              items: [{type: 'autogenerated', dirName: 'reference/models/fct'}],
            },
          ],
        },
        {
          type: 'category',
          label: 'Schemas',
          items: [{type: 'autogenerated', dirName: 'reference/schemas'}],
        },
        {
          type: 'category',
          label: 'CLI',
          items: [{type: 'autogenerated', dirName: 'reference/cli'}],
        },
        {
          type: 'category',
          label: 'Macros',
          items: [{type: 'autogenerated', dirName: 'reference/macros'}],
        },
        'reference/glossary',
        'reference/manifest',
        'reference/model-card',
      ],
    },
  ],

  dbtSidebar: [
    {
      type: 'category',
      label: 'DBT',
      items: [{type: 'autogenerated', dirName: 'learn-dbt'}],
    },
  ],

  mlSidebar: [
    {
      type: 'category',
      label: 'Machine Learning',
      items: [{type: 'autogenerated', dirName: 'machine-learning'}],
    },
  ],

  findingsSidebar: [
    {
      type: 'category',
      label: 'Attributed Findings',
      items: [
        'attributed-findings/index',
        'attributed-findings/sao-paulo-2021',
      ],
    },
  ],
};

export default sidebars;
